spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8383/realms/spring-keycloak-realm
          jwk-set-uri: http://localhost:8383/realms/spring-keycloak-realm/protocol/openid-connect/certs